stages:
  - test
  - sast
  - dependency-check
  - build
  - build-operator
  - scan
  - push

variables:
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

run-tests:
  stage: test
  image: python:3.12-slim
  before_script:
    - pip install -r backend/requirements.txt
  script:
    - cd backend
    - python -m pytest tests/test_main.py -v
        --junitxml=../report.xml
        --cov=.
        --cov-report=xml:../coverage.xml
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.xml
    expire_in: 1 hour

sonarcloud-check:
  stage: sast
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: sonar-cache
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
        -Dsonar.projectKey=$SONAR_PROJECT_KEY
        -Dsonar.organization=$SONAR_ORGANIZATION
        -Dsonar.host.url=$SONAR_HOST_URL
        -Dsonar.login=$SONAR_TOKEN
        -Dsonar.python.coverage.reportPaths=coverage.xml
  needs:
    - run-tests
  allow_failure: false

dependency-check:
  stage: dependency-check
  image: python:3.13-slim
  script:
    - pip install pip-audit
    - mkdir -p reports
    - pip-audit -r backend/requirements.txt -r backend/constraints.txt
        --format json
        --output reports/pip-audit-report.json
  artifacts:
    when: always
    paths:
      - reports/
    expire_in: 1 week
  allow_failure: false

docker-build-backend:
  stage: build
  image: docker:24-dind
  services:
    - docker:24-dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  script:
    - docker build -t $DOCKER_USER/url-shortener-backend:$IMAGE_TAG ./
    - docker save $DOCKER_USER/url-shortener-backend:$IMAGE_TAG > backend-image.tar
  artifacts:
    paths:
      - backend-image.tar
    expire_in: 1 hour
  needs:
    - sonarcloud-check
    - dependency-check

docker-build-frontend:
  stage: build
  image: docker:24-dind
  services:
    - docker:24-dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  script:
    - docker build -t $DOCKER_USER/url-shortener-frontend:$IMAGE_TAG  ./frontend .
    - docker save $DOCKER_USER/url-shortener-frontend:$IMAGE_TAG > frontend-image.tar
  artifacts:
    paths:
      - frontend-image.tar
    expire_in: 1 hour
  needs:
    - sonarcloud-check
    - dependency-check

build-operator:
  stage: build-operator
  image: docker:24-dind
  services:
    - docker:24-dind
  rules:
    - changes:
        - remediation/*
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    - git remote set-url origin https://oauth2:$GITLAB_TOKEN@gitlab.com/vaibhavC54/url-shortner.git
    - git config --global user.email "ci@gitlab.com"
    - git config --global user.name "CI Pipeline"
  script:
    - docker build -t $DOCKER_USER/remediation-operator:$CI_COMMIT_SHORT_SHA ./remediation
    - docker push $DOCKER_USER/remediation-operator:$CI_COMMIT_SHORT_SHA
    - docker tag $DOCKER_USER/remediation-operator:$CI_COMMIT_SHORT_SHA $DOCKER_USER/remediation-operator:latest
    - docker push $DOCKER_USER/remediation-operator:latest
    - git checkout -B main
    - 'sed -i "s|$DOCKER_USER/remediation-operator:.*|$DOCKER_USER/remediation-operator:$IMAGE_TAG|g" k8s/manifests/operators/remediation-deployment.yaml'
    - git add k8s/manifests/operators/remediation-deployment.yaml
    - git diff-index --quiet HEAD || git commit -m "chore- update remediation operator image to $IMAGE_TAG [ci skip]"
    - git push origin HEAD:main

trivy-scan-backend:
  stage: scan
  image: docker:24-dind
  services:
    - docker:24-dind
  before_script:
    - apk add --no-cache curl
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
  script:
    - docker load < backend-image.tar
    - trivy image
        --exit-code  1
        --ignore-unfixed
        --severity HIGH,CRITICAL
        --format table
        $DOCKER_USER/url-shortener-backend:$IMAGE_TAG
  needs:
    - docker-build-backend
  allow_failure: false

trivy-scan-frontend:
  stage: scan
  image: docker:24-dind
  services:
    - docker:24-dind
  before_script:
    - apk add --no-cache curl
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
  script:
    - docker load < frontend-image.tar
    - trivy image
        --exit-code  1
        --ignore-unfixed
        --severity HIGH,CRITICAL
        --format table
        $DOCKER_USER/url-shortener-frontend:$IMAGE_TAG
  needs:
    - docker-build-frontend
  allow_failure: false

push-image:
  stage: push
  image: docker:24-dind
  services:
    - docker:24-dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  script:
    - docker load < backend-image.tar
    - docker load < frontend-image.tar
    # Push backend image
    - docker push $DOCKER_USER/url-shortener-backend:$IMAGE_TAG
    - docker tag $DOCKER_USER/url-shortener-backend:$IMAGE_TAG $DOCKER_USER/url-shortener-backend:latest
    - docker push $DOCKER_USER/url-shortener-backend:latest 
    # Push frontend image
    - docker push $DOCKER_USER/url-shortener-frontend:$IMAGE_TAG
    - docker tag $DOCKER_USER/url-shortener-frontend:$IMAGE_TAG $DOCKER_USER/url-shortener-frontend:latest
    - docker push $DOCKER_USER/url-shortener-frontend:latest
  needs:
    - trivy-scan-backend
    - trivy-scan-frontend
  allow_failure: false
  only:
    - main