backend:
  replicaCount: 2
  image:
    repository: vaibhav04c/url-shortener-backend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

frontend:
  replicaCount: 2
  image:
    repository: vaibhav04c/url-shortener-frontend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  resources:
    requests:
      cpu: 10m       
      memory: 32Mi   
    limits:
      cpu: 50m
      memory: 64Mi

ingress:
  enabled: true
  className: nginx
  host: s.trendstimes.in
  tls: true
  tlsSecretName: url-shortener-tls

config:
  awsRegion: ap-south-1
  dynamodbTable: url-shortener
  baseUrl: https://s.trendstimes.in
  redisHost: url-shortener-redis
  redisPort: "6379"
  shortCodeLength: "7"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilizationPercentage: 70

redis:
  enabled: true
  image: redis:7-alpine
  port: 6379
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

serviceAccount:
  create: true
  name: url-shortener-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::773384830615:role/url-shortener-sa-role