sonar.projectKey=vaibhavC54_url-shortner
sonar.organization=vaibhavc54
sonar.projectName=URL Shortener
sonar.projectVersion=1.0
sonar.source=app
sonar.exclusions=app/tests/**
sonar.tests=app/tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8