apiVersion: v1
kind: ServiceAccount
metadata:
  name: remediation-operator-sa
  namespace: url-shortener

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: remediation-operator-role
  namespace: url-shortener
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: remediation-operator-rolebinding
  namespace: url-shortener
subjects:
  - kind: ServiceAccount
    name: remediation-operator-sa
    namespace: url-shortener
roleRef:
  kind: Role
  name: remediation-operator-role
  apiGroup: rbac.authorization.k8s.io