apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-config
    namespace: {{ .Release.Namespace }}
    labels:
        app: {{ .Release.Name }}
data:
    AWS_REGION: {{ .Values.config.awsRegion | quote }}
    DYNAMODB_TABLE: {{ .Values.config.dynamodbTable | quote }}
    BASE_URL: {{ .Values.config.baseUrl | quote }}
    REDIS_HOST: {{ .Values.config.redisHost | quote }}
    REDIS_PORT: {{ .Values.config.redisPort | quote }}
    SHORT_CODE_LENGTH: {{ .Values.config.shortCodeLength | quote }}